
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Top(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

   reg						clk_25;
   reg						rstn_25;

   reg [3:0]					cnt_rstn_25;

   wire [7:0]					key;


//=======================================================
//  Structural coding
//=======================================================

   function [6:0] hex_to_sseg(input [3:0] x);
      case (x)
        4'h0 : hex_to_sseg = 7'b1000000;
        4'h1 : hex_to_sseg = 7'b1111001;
        4'h2 : hex_to_sseg = 7'b0100100;
        4'h3 : hex_to_sseg = 7'b0110000;
        4'h4 : hex_to_sseg = 7'b0011001;
        4'h5 : hex_to_sseg = 7'b0010010;
        4'h6 : hex_to_sseg = 7'b0000010;
        4'h7 : hex_to_sseg = 7'b1111000;
        4'h8 : hex_to_sseg = 7'b0000000;
        4'h9 : hex_to_sseg = 7'b0011000;
        4'hA : hex_to_sseg = 7'b0001000;
        4'hB : hex_to_sseg = 7'b0000011;
        4'hC : hex_to_sseg = 7'b1000110;
        4'hD : hex_to_sseg = 7'b0100001;
        4'hE : hex_to_sseg = 7'b0000110;
        4'hF : hex_to_sseg = 7'b0001110;
      endcase
   endfunction

//   SyncReset clk25_reset_sync (
//     .IN_RST(key_reset),
//     .CLK(clk_25),
//     .OUT_RST(rstn_25)
//   );

   always @(posedge CLOCK_50) begin
      clk_25 <= ~ clk_25;
   end

   initial begin
      rstn_25 <= 1'b1;
      cnt_rstn_25 <= 4'd0;
   end
   always @(posedge clk_25) begin
      if (cnt_rstn_25 < 4'd10) begin
	 rstn_25 <= 1'b0;
	 cnt_rstn_25 <= cnt_rstn_25 + 4'd1;
      end
      else begin
	 rstn_25 <= 1'b1;
      end
   end

   assign LEDR = 0;

   assign HEX0 = hex_to_sseg(key[3:0]);
   assign HEX1 = hex_to_sseg(key[7:4]);
   assign HEX2 = 7'b1111111;
   assign HEX3 = 7'b1111111;
   assign HEX4 = 7'b1111111;
   assign HEX5 = 7'b1111111;

   assign VGA_CLK = ~ clk_25;
   assign VGA_SYNC_N = 1;

   mkFPGATop_DE10Std pong(
			  .CLK(clk_25),
			  .RST_N(rstn_25),

			  .color1(SW[0:0]),
			  .color2(SW[1:1]),

			  .kbclk(PS2_CLK),
			  .kbdata(PS2_DAT),
			  .key(key),

			  .vga_r(VGA_R),
			  .vga_g(VGA_G),
			  .vga_b(VGA_B),
			  .vga_hs(VGA_HS),
			  .vga_vs(VGA_VS),
			  .vga_blank_n(VGA_BLANK_N)
			  );

endmodule // Top
