package Island1 (mkIsland, Island(..)) where

import Global
import Shape
import Color

islandWidthC :: XSize
islandWidthC = fromInteger islandWidth

islandHeightC :: YSize
islandHeightC = fromInteger islandHeight

islandLeftC :: XCoord
islandLeftC = fromInteger ((hSize - islandWidth) `div` 2)

islandLowC :: YCoord
islandLowC = fromInteger ((vSize - islandHeight) `div` 2) -- ((vSize `div` 2) + islandHeight + paddleWidth)

interface Island =
   shape :: Shape;
   inside :: XCoord -> XCoord -> YCoord -> YCoord -> YSize -> (Bool,Bool,Bool,Bool,YSize)

mkIsland :: Module Island
mkIsland =
  module
    islandRect :: Shape <- mkRectangle
                              islandLeftC islandWidthC
                              islandLowC islandHeightC
                              cRed

    let inside1 :: XCoord -> YCoord -> Bool
        inside1 x y =
              x > islandLeftC &&
	      x < islandLeftC + islandWidthC &&
	      y > islandLowC &&
	      y < islandLowC + islandHeightC

    interface
        shape = islandRect

        inside x0 x1 y0 y1 _ =
            (inside1 x0 y0, inside1 x0 y1, inside1 x1 y0, inside1 x1 y1, 0)

