
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Top(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

   reg						rstn_50;
   reg [3:0]					cnt_rstn_50;

   /*
   reg						clk_25;
   reg						rstn_25;
   reg [3:0]					cnt_rstn_25;
    */

   reg						clk_64;
   reg						rstn_64;
   reg [3:0]					cnt_rstn_64;

   wire						vga_clk;
   wire						vga_rstn;

//=======================================================
//  Structural coding
//=======================================================

//   SyncReset clk25_reset_sync (
//     .IN_RST(key_reset),
//     .CLK(clk_25),
//     .OUT_RST(rstn_25)
//   );

   initial begin
      rstn_50 <= 1'b1;
   end
   always @(posedge CLOCK_50) begin
      if (cnt_rstn_50 < 4'd10) begin
	 rstn_50 <= 1'b0;
	 cnt_rstn_50 <= cnt_rstn_50 + 4'd1;
      end
      else begin
	 rstn_50 <= 1'b1;
      end
   end

   /*
   always @(posedge CLOCK_50) begin
      clk_25 <= ~ clk_25;
   end

   initial begin
      rstn_25 <= 1'b1;
      cnt_rstn_25 <= 4'd0;
   end
   always @(posedge clk_25) begin
      if (cnt_rstn_25 < 4'd10) begin
	 rstn_25 <= 1'b0;
	 cnt_rstn_25 <= cnt_rstn_25 + 4'd1;
      end
      else begin
	 rstn_25 <= 1'b1;
      end
   end
    */

   pll64 pll64_inst (.refclk(CLOCK_50),
		     .rst(~ rstn_50),
		     .outclk_0(clk_64)
		     );

   initial begin
      rstn_64 <= 1'b1;
      cnt_rstn_64 <= 4'd0;
   end
   always @(posedge clk_64) begin
      if (cnt_rstn_64 < 4'd10) begin
	 rstn_64 <= 1'b0;
	 cnt_rstn_64 <= cnt_rstn_64 + 4'd1;
      end
      else begin
	 rstn_64 <= 1'b1;
      end
   end

   assign vga_clk = clk_64;
   assign vga_rstn = rstn_64;

   assign LEDR = 0;

   assign HEX0 = 7'b1111111;
   assign HEX1 = 7'b1111111;
   assign HEX2 = 7'b1111111;
   assign HEX3 = 7'b1111111;
   assign HEX4 = 7'b1111111;
   assign HEX5 = 7'b1111111;

   assign VGA_CLK = ~ vga_clk;
   assign VGA_SYNC_N = 1;

   mkFPGATop_DE10Std pong(
			  .CLK(vga_clk),
			  .RST_N(vga_rstn),

			  .color1(SW[0:0]),
			  .color2(SW[1:1]),
			  .autoL(SW[2:2]),
			  .autoR(SW[3:3]),

			  .userLup(KEY[3:3]),
			  .userLdown(KEY[2:2]),
			  .userRup(KEY[1:1]),
			  .userRdown(KEY[0:0]),

			  .vga_r(VGA_R),
			  .vga_g(VGA_G),
			  .vga_b(VGA_B),
			  .vga_hs(VGA_HS),
			  .vga_vs(VGA_VS),
			  .vga_blank_n(VGA_BLANK_N)
			  );

endmodule // Top
